trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:



- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
        **
        !.git/**
        !*.yml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- script:  |
   ls -la
