trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:



- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
        **
        !.git/**
        !*.yml
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy Source File to Staging Directory'

- script:  |
   ls -la

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Pubish Staging Directory Contents into artificats'
